name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Tag
      uses: ydataai/create-tag@v1
      with:
        tag: 'v1.0.0'
        message: 'Release v1.0.0'
